### ISSUE TITLE
mac_arm64 not work

### ISSUE THREAD

**Issue by kingking888** [KasperskyLab/hrtng#5]
dlopen(/Users/kingking/.idapro/plugins/hrtng.dylib, 0x0002):
/Users/kingking/.idapro/plugins/hrtng.dylib: can't load file

**Comment by srgblv** [comment]
Try to move the plugin into "IDA directory". For Ida9 for Mac it will be `/Applications/IDA Professional 9.0.app/Contents/MacOS/plugins` dir.  Installing into user directory does not guarantee compatibility of the plugin with IDA version because IDA API changes too often.
From my experience I do not recommend [sharing plugins between ida installs](
https://hex-rays.com/blog/igors-tip-of-the-week-103-sharing-plugins-between-ida-installs)

**Comment by kingking888** [comment]
Thanks a lot, it's work at last
